services:
  metabase-db:
    image: postgres:18-alpine
    container_name: metabase-db
    env_file: .env
    restart: always
    volumes:
      - ${KD_DIR}:/var/lib/postgresql/data
    networks:
      - kidcredo
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    env_file: .env
    depends_on:
      - metabase-db
    networks:
      - kidcredo
networks:
  kidcredo:
    external: true